BakeBFlake/Controllers/CartController.cs
using BakeBFlake.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BakeBFlake.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/

        public ActionResult Index()
        {
            var cart = Session["cart"];
            return View(cart);
        }

        public bool RemoveItem(Int32 id)
        {
            List<OrderDetails> cart = (List<OrderDetails>)Session["cart"];
            var item = cart.Find(x => x.Id == id);
            if (item != null)
            {
                cart.Remove(item);
                return true;
            }
            else
            {
                return false;
            }
        }

        public ActionResult Checkout()
        {
            //save order to db and return order model
            var order = new Order() {Id= 19127872, TotalPrice = 50};

            //empty cart
            Session["cart"] = new List<OrderDetails>();

            return View(order);
        }

    }
}

BakeBFlake/Controllers/CustomerController.cs
using BakeBFlake.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BakeBFlake.Controllers
{
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/

        public ActionResult Index(string id, string firstName, string lastName, string address)
        {
            ViewBag.Message = "Customers List";

            return View(getUsers());
        }

        private List<User> getUsers()
        {
            var user1 = new User();
            user1.Id = 123;
            user1.Name = "Ido";
            user1.LastName = "Ganzer";
            user1.Address = "Bla bla 30";
            user1.PhoneNumber = "5543253";
            user1.Password = "abcde";
            user1.Prefered = true;

            var user2 = new User();
            user2.Id = 456;
            user2.Name = "Ido2";
            user2.LastName = "Ganzer2";
            user2.Address = "Bla bla 32";
            user2.PhoneNumber = "56785467";
            user2.Password = "fghjf";
            user2.Prefered = false;

            var users = new List<User>();
            users.Add(user1);
            users.Add(user2);

            return users;
        }

        [HttpPost]
        public ActionResult Edit(User customer)
        {
            ViewBag.Message = "Customers List";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var user1 = new User();
            user1.Id = 123;
            user1.Name = "Ido";
            user1.LastName = "Ganzer";
            user1.Address = "Bla bla 30";
            user1.PhoneNumber = "5543253";
            user1.Password = "abcde";
            user1.Prefered = true;

            return View(user1);
        }

        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
        }

    }
}

BakeBFlake/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("PageScripts", false)
    </head>
    <body>
        <header>
            <div>
                <div>
                    <div class="pull-left"><h1>Bake N' Flake</h1></div>
                    <div class="pull-left">
                        <img src="~/Images/logo.jpg" />
                    </div>
                </div>
                <div class="pull-right">
                    @*<section class="float-right" id="login">
                        @Html.Partial("_LoginPartial")
                    </section>*@
                    <ul class="nav nav-pills">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>

                        @if (Session["LoginUser"] != null) 
                        {
                            <li hidden=@ViewBag.isLoggedIn>@Html.ActionLink("My Orders", "Index", "Home")</li>
                            <li data-counter="@Session["ItemsInCart"]" id="cartDisplay">@Html.ActionLink("Cart (" + Session["ItemsInCart"] +")", "Index", "Cart")</li>
                            
                            if ((Session["LoginUser"] as BakeBFlake.Models.User).Prefered)
                            { 
                                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                            }

                            <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Home")</li>
                        }
                        
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li></li>
                    </ul>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="container-fluid clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="container">
                <div class="pull-left">
                    <p>&copy; @DateTime.Now.Year Bake N' Flake Backery Shop</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>